<testsuite errors="0" failures="1" name="unittest.TestSuite" tests="1" time="0.000">
  <testcase classname="CreateNewModuleTests.CreateNewModuleTests" name="testCreateLibrary" time="0.0000">
    <failure type="exceptions.AssertionError">File not found: resources/TemplateLibrary/__init__.py
  File "C:\Program Files\Python 2.6\lib\unittest.py", line 279, in run
    testMethod()
  File "E:\devel\src\toolkit_clean\tools\StartNewModule\tests\CreateNewModuleTests.py", line 20, in testCreateLibrary
    CreateNewModule.CreateLibrary(projectRoot, projectName, rootForTemplateFiles)
  File "E:\devel\src\toolkit_clean\tools\StartNewModule\src\CreateNewModule.py", line 46, in CreateLibrary
    ConfigureFile("%s/TemplateLibrary/__init__.py" % _rootForTemplateFiles, "%s/%s/__init__.py" % (_projectRoot, _libraryName), dictionary)
  File "E:\devel\src\toolkit_clean\tools\StartNewModule\src\CreateNewModule.py", line 4, in ConfigureFile
    assert os.path.exists(_source), "File not found: %s" % _source
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
